### ISSUE TITLE
App crashes while playing sounds

### ISSUE THREAD

**Issue by Schnurber** [luanpotter/audioplayers#191]
After a while playing sounds my app crashes with the following exception:
`E/AndroidRuntime(13622): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime(13622): 	at xyz.luan.audioplayers.WrappedSoundPool.onLoadComplete(WrappedSoundPool.java:182)`
is this a bug?

**Comment by luanpotter** [comment]
Hi, @oth-aw :)

This was also reported by John John, I think I fixed now in 0.13.1, would you help testing out in your app, please?

**Comment by zyq666** [comment]
I'm using the version of 0.13.1, but I still crashed while playing sounds.

**Comment by Brazol** [comment]
I have the same exception with different stack:

```
E/AudioplayersPlugin( 2752): Unexpected error!
E/AudioplayersPlugin( 2752): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AudioplayersPlugin( 2752): 	at xyz.luan.audioplayers.WrappedSoundPool.setVolume(WrappedSoundPool.java:113)
E/AudioplayersPlugin( 2752): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:61)
E/AudioplayersPlugin( 2752): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:41)
```
looks like streamId is used but never initialized in WrappedSoundPool?

**Comment by burak-yildirim** [comment]
I also have the same exception: 
```
E/AudioplayersPlugin(11514): Unexpected error!
E/AudioplayersPlugin(11514): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AudioplayersPlugin(11514): 	at xyz.luan.audioplayers.WrappedSoundPool.setVolume(WrappedSoundPool.java:113)
E/AudioplayersPlugin(11514): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:61)
E/AudioplayersPlugin(11514): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:41)
```

```AudioplayersPlugin.handleMethodCall``` method calls ```player.setVolume()``` without initializing ```streamId``` of the ```player``` (which is a _WrappedSoundPool_ in my case since i use _PlayerMode.LOW_LATENCY_).

If I try to play the sound right after creating my audiocache, I recieve this error. if I wait couple of seconds after creating my audiocaches (i use more than one) sometimes some of them gives this error but others don't even though I initialize them at the same time.

**Comment by burak-yildirim** [comment]
After struggling so hard (and maybe regretting being a developer couple of times) this is my temporary solution for the seekers out there (explanation is after code):
```
import 'package:flutter/services.dart';
import 'package:audioplayers/audio_cache.dart';
import 'package:audioplayers/audioplayers.dart';

class MyPlayer {
  AudioCache _audioCache;
  String _soundFile;

  MyPlayer(String soundFile) {
    _soundFile = soundFile;
    _init();
  }

  void _init() {
    var audioPlayer = AudioPlayer(mode: PlayerMode.LOW_LATENCY)
      ..setReleaseMode(ReleaseMode.STOP);
    _audioCache = AudioCache(fixedPlayer: audioPlayer);
  }

  Future<void> load() async {
    await _audioCache.load(_soundFile);
  }

  Future<void> play() async {
    try {
      await _audioCache.play(_soundFile);
    } on PlatformException catch (ex) {
      print('Caught exception: $ex');
      _init();
      await load();
      print('re-loaded');
      _audioCache.play(_soundFile);
    } catch (ex, st) {
      print('Exception occured: $ex');
      print('StackTrace: $st');
    }
  }
}
```

I am basically trying to achieve sort of buttons play 1sec sound file(asset) every time they are tapped on the same screen. Each button has different AudioCache because i need to use fixed AudioPlayer for fast reaction but also buttons shouldn't block eachother. When I get the exception I mentioned in the above comment, I couldn't play the asset file again with the same AudioCache. Restarting/Re-installing my app just breakes random buttons. So I wrapped the AudioCache according to my needs . ```play``` method just rebuilds the AudioCache if it fails to play the sound, and rebuilding just works !

**Comment by erickzanardo** [comment]
Should be fixed on newer versions
