### ISSUE TITLE
Partially played if you play a large audio file remotely.

### ISSUE THREAD

**Issue by somaria** [luanpotter/audioplayers#428]
I just realized that for some of the audio files in my Android app, if the file is of a larger size, it will suddenly cut off when playing.  So only first part of the audio is played.  If the audio file size is small, it is ok.

This happened when playing remotely and also if the isLocal is enabled.  

Anyone encountered similar issues for Android?

**Comment by saisantosh2095** [comment]
Even i had a issue when using "PlayerMode.LOW_LATENCY" .  But it was fixed when i changed it to 
 "PlayerMode.MEDIA_PLAYER"

**Comment by somaria** [comment]
@saisantosh2095 

Yes, that solved it!  Thanks!

This issue can be closed!

**Comment by CristianSavin** [comment]
@saisantosh2095 Can you give me please an example how to make this work? I had the same issue and I set PlayerMode to MEDIA_PLAYER when I initialize my player but this not solved problem.

**Comment by Gradergage** [comment]
@saisantosh2095 Tried to use this with AudioCache fixedPlayer, but it doesn't work

**Comment by saisantosh2095** [comment]
@Gradergage 
So i have been using this code to play large audio files.This works good fo me.

`AudioPlayer bgmPlayer = new AudioPlayer(mode: PlayerMode.MEDIA_PLAYER);`
`bgmPlayer.setVolume(1.0);`
`bgmPlayer.onPlayerCompletion.listen((event) {`
    `if(autoPlay) { `
       `playNextTrack();` 
   ` }`
 `});`
` bgmPlayer.play(localAudioPath[widget.tracks[currentVideoIndex].id],isLocal: true);`

**Comment by Gradergage** [comment]
@saisantosh2095 IDK how, it worked once, but now isn't:
Init
```
    player =
        AudioPlayer(mode: PlayerMode.MEDIA_PLAYER, playerId: "main_player");
    cache = AudioCache();
```
usage
```
    File track = await cache.load(path);
    player.setVolume(1.0);
    player.play(track.path, isLocal: true);
```
I have this log as result
```
position changed 0:03:52.771000
V/MediaPlayer(31043): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(31043): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(31043): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(31043): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/flutter (31043): AudioPlayerState.COMPLETED
```
track was 4:48 length and stopped at 3:52, any tack longer than minute drops at some point as completed

**Comment by Gradergage** [comment]
```
I/flutter ( 8334): AudioPlayerState.PLAYING
I/flutter ( 8334): _platformCallHandler call audio.onDuration {value: 137665, playerId: main_player}
I/flutter ( 8334): _platformCallHandler call audio.onDuration {value: 137665, playerId: main_player}
I/flutter ( 8334): _platformCallHandler call audio.onCurrentPosition {value: 79587, playerId: main_player}
I/flutter ( 8334): position changed 0:01:19.587000
I/flutter ( 8334): _platformCallHandler call audio.onDuration {value: 137665, playerId: main_player}
I/flutter ( 8334): _platformCallHandler call audio.onCurrentPosition {value: 79614, playerId: main_player}
I/flutter ( 8334): position changed 0:01:19.614000
I/flutter ( 8334): _platformCallHandler call audio.onSeekComplete {value: true, playerId: main_player}
V/MediaPlayer( 8334): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 8334): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 8334): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 8334): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/flutter ( 8334): _platformCallHandler call audio.onComplete {value: true, playerId: main_player}
```
This is audioplayers log, track doesn't completed and this is clearly. But IDK why it stops playing

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
