### ISSUE TITLE
The plugin `audioplayers` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command. Process finished with exit code 1

### ISSUE THREAD

**Issue by fernan542** [luanpotter/audioplayers#719]
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The plugin `audioplayers` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.
Process finished with exit code 1

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.22.5 at C:\src\flutter\flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by erickzanardo** [comment]
As the log says, you need to migrate your app to Android embedding v2, you can follow the guide informed on the log.

**Comment by bhavesh350** [comment]
As the log says, 
The plugin **audioplayers** requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.


So with me is the same issue that app is already migrated to the Android embedding v2, but error is specific to this audioplayers plugin, please help to sort this issue.
Thanks

**Comment by fernan542** [comment]
If I can remember what I did last time, I updated the package version and do:
`flutter clean`
`flutter pub cache repair`
`flutter pub get`

**Comment by bhavesh350** [comment]
Thanks @fernan542 for your reply, but it still giving same issue
The plugin `audioplayers` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this
command.
:(

**Comment by bhavesh350** [comment]
Thanks for the steps to solve, but it did not work, I am still getting same issue and saying 
The plugin `audioplayers` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this
command.

**Comment by bhavesh350** [comment]
@erickzanardo can you please tell if you can help here?

**Comment by rakeshparveen5** [comment]
Facing the same issue

**Comment by Sundin** [comment]
Read the migration steps carefully. For me it was enough to replace `android:name="io.flutter.app.FlutterApplication"` with `android:name="${applicationName}"` inside `android/app/src/main/AndroidManifest.xml`.
