### ISSUE TITLE
AudioplayersPlugin.h file not found while creating archive

### ISSUE THREAD

**Issue by prof18** [luanpotter/audioplayers#80]

**Comment by prof18** [comment]
Resolved, I've figured out that I was opening the project instead of the workspace

**Comment by YourksChan** [comment]
I also encountered the same problem, can not solve

**Comment by rabihmb** [comment]
I have the same issue, I applied the following commands; and still failed to run.

```
flutter packages get
sudo gem install cocoapods
pod repo update
pod install
```

in addition, I ran the commands `brew install cocoapods`

any idea?
