### ISSUE TITLE
'flutter pub add audioplayers' = The binary version of its metadata is 1.5.1, expected version is 1.1.15

### ISSUE THREAD

**Issue by 3SCadmin** [luanpotter/audioplayers#941]
July 4th 2021, running flutter 2.2.3 on windows, with physical Android device.

Just running the package installation command 'flutter pub add audioplayers'   is enough to subsequently crash the build process.

It spits out a bunch of error messages, starts with:

**e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: C:/Users/admin/.gradle/caches/transforms-2/files-2.1/24fa3aa8d2270e5eb067bbe36e9b7563/jetified-kotlin-stdlib-1.5.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:/Users/admin/.gradle/caches/transforms-2/files-2.1/77bab1911042ab2c6d5cc0b2e2ee053c/jetified-kotlin-stdlib-common-1.5.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.**

'flutter pub remove audioplayers' .. and the project builds again.

**Comment by luanpotter** [comment]
What version of AP were you using? I believe this was fixed by 0.19.1 (released a few days ago)

**Comment by killerm250m** [comment]
Me too I am using the latest version (0.19.1)

**Comment by 3SCadmin** [comment]
> What version of AP were you using? I believe this was fixed by 0.19.1 (released a few days ago)

0.19.1
After some googling I was able to move beyond the error.
1.) edited **android\build.gradle** in the project.
2.) changed **ext.kotlin_version = '1.3.50'** to **ext.kotlin_version = '1.4.32'**

I have no idea what that does, just copied what someone else said worked.
For my education:
Is this a package specific issue?  A flutter related issue? Something specific to my dev environment settings?

**Comment by GuerrillaGambit** [comment]
Faced the exact same issue, but @3SCadmin 's solution worked for now. Seems like a debug is required though.

**Comment by killerm250m** [comment]
@3SCadmin solution worked for me, Thanks!

**Comment by lahirudx** [comment]
Same issue here. @3SCadmin's solution worked for me. I have changed  **ext.kotlin_version = '1.5.10'**. It's also workded.

**Comment by luanpotter** [comment]
Thanks for the investigations! We should definitely add that to our FAQ. I believe the issue is your flutter projects made in the past had an old kotlin version and the newer versions of audioplayers are not compatible, thus requiring the update mentioned.

**Comment by 3SCadmin** [comment]
>  I believe the issue is your flutter projects made in the past 

Are you sure about that?

I can reproduce the error with:
- flutter create audio_test
- code audio_test
(switch windows)
- flutter pub add audioplayers
- flutter run

flutter doctor is happy... what else do I need to upgrade?

**Comment by dvorapa** [comment]
> > I believe the issue is your flutter projects made in the past
> 
> Are you sure about that?
> 
> I can reproduce the error with:
> 
>     * flutter create audio_test
> 
>     * code audio_test
>       (switch windows)
> 
>     * flutter pub add audioplayers
> 
>     * flutter run
> 
> 
> flutter doctor is happy... what else do I need to upgrade?

Same here. Time to time I run `flutter create my_old_project_2021` and just update the whole project platform codebase. Also I regularly update Android Studio with its Kotlin (currently 1.5.21). But the default flutter project has still 1.3.50 in its default android/build.gradle file, (perhaps due to backwards compatibility?). So all the new flutter audio player projects still must get this error.

**Comment by itanium21** [comment]
Unfortunately for me, changing ext.kotlin_version to '1.5.21' (the one from Android Studio) didn't help.
`Running Gradle task 'assembleDebug'...

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.19.1\android\build.gradle' line: 28

* What went wrong:
A problem occurred evaluating project ':audioplayers'.
> java.lang.OutOfMemoryError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':audioplayers'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1`

Any ideas?

**Comment by dvorapa** [comment]
I used `ext.kotlin_version = '1.4.21'`, maybe it will work for you?

**Comment by luanpotter** [comment]
I believe this has been fixed by https://github.com/luanpotter/audioplayers/pull/992

**Comment by dvorapa** [comment]
I tried `flutter create` with Flutter 2.5.1 and then used audioplayers 0.20.1 in it. The default app template created is still showing `ext.kotlin_version = '1.3.50'`. And the build is still failing because of the error described above. Adjusting 1.3.50 to 1.4.32 solves the issue, as stated before:

> > What version of AP were you using? I believe this was fixed by 0.19.1 (released a few days ago)
> 
> 0.19.1
> After some googling I was able to move beyond the error.
> 1.) edited **android\build.gradle** in the project.
> 2.) changed **ext.kotlin_version = '1.3.50'** to **ext.kotlin_version = '1.4.32'**
> 
> I have no idea what that does, just copied what someone else said worked.
> For my education:
> Is this a package specific issue? A flutter related issue? Something specific to my dev environment settings?

Maybe it should just be added to the readme?
